config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
  get '/home_pages', to: 'home#index', as: 'home_pages'
  resources :groups, only: [:index, :new, :create, :destroy] do
    resources :entities, only: [:index, :new, :create, :destroy]
  end
  
  # resources :entities, only: [:new, :create]
end

app/models/ability.rb
class Ability
  include CanCan::Ability
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_entities, dependent: :destroy
  has_many :groups, through: :group_entities
  validates :name, :author, :amount, presence: true

  def date
    date = ''
    date += "#{created_at.day} "
    date += "#{Date::ABBR_MONTHNAMES[created_at.month]} "
    date += created_at.year.to_s
    date
  end
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  # has_many :group_entities, foreign_key: :group_id
  # has_many :entities, through: :group_entities, foreign_key: :group_id
  # has_many :entities, foreign_key: :group_id
  # has_and_belongs_to_many :entities, foreign_key: :group_id, dependent: :destroy
  has_many :group_entities, dependent: :destroy
  has_many :entities, through: :group_entities

  validates :name, presence: true
  validates :icon, presence: true

  def total_amount
    total = 0
    entities.each do |t|
      total += t.amount
    end
    total
  end

  def date
    date = ''
    date += created_at.day.to_s
    date += (Date::ABBR_MONTHNAMES[created_at.month]).to_s
    date += created_at.year.to_s
    date
  end
end

app/models/group_entity.rb
class GroupEntity < ApplicationRecord
  belongs_to :group
  belongs_to :entity

  validates :entity, uniqueness: { scope: :group, message: 'already exists in this category' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entities, foreign_key: :author_id, dependent: :destroy
  has_many :groups, foreign_key: :author_id, dependent: :destroy
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |user_params| user_params.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:name, :email, :password)
    end
  end

  def after_sign_in_path_for(_resource)
    groups_path
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @entities = @group.entities.order(created_at: :desc)
  end

  def new
    @new_entity = Entity.new
    @group = Group.find(params[:group_id])
    @user_groups = Group.where(author: current_user)
  end

  def create
    entity = Entity.new(name: entity_params[:name], author_id: current_user.id, amount: entity_params[:amount])

    if entity.save
      groups = Group.find(params[:group_id])
      GroupEntity.create(entity_id: entity.id, group_id: groups.id)
      flash[:notice] = 'Transaction created successfully'
      redirect_to group_entities_path
    else
      flash[:error] = 'Failed to create transaction'
      render :new
    end
  end

  def destroy
    @transaction = Entity.find(params[:id])

    return unless @transaction.destroy

    flash[:success] = 'Transaction deleted successfully.'
    redirect_to group_entities_path(params[:group_id])
  end

  private

  def entity_params
    params.require(:entity).permit(:name, :amount, :author_id, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    if user_signed_in?
      @groups = Group.all.order(created_at: :desc).includes(:entities).where(author: current_user)
    else
      @page_title = 'Home'
      redirect_to home_path
    end
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      flash[:notice] = 'Category created successfully'
      redirect_to groups_path
    else
      puts @group.errors
      puts @group.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @group = Group.find(params[:id])
    return unless @group.destroy

    flash[:success] = 'Category deleted successfully.'
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(_user)
    new_user_session_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entities/index.html.erb
<header class="page-header">
<%= link_to home_pages_path do %><%= image_tag "left-arrow.png", class: "nav-icon" %> <% end %>
<h1>Transactions</h1>
</header>
<section>
<div class="top-card">
<span class="primary-text">Total amount</span>
<span class="sec-text"><%= @group.total_amount %></span>
</div>
<div class="cards-container transactions-container">
<% @entities.each do |entity| %>
<div class="card">
<div class="column">
<span class="primary-text"><%= entity.name %></span>
<span class="date-stamp"><%= entity.date%></span>
</div>
<div class="column last-col">
<span class="sec-text"><%= entity.amount%></span>
</div>
</div>
<% end %>
<%= link_to "ADD TRANSACTION", new_group_entity_path(@group), class: "btn-add" %>
 </div>
</section>

app/views/entities/new.html.erb
<header class="page-header">
<%= link_to home_pages_path do %><%= image_tag "left-arrow.png", class: "nav-icon" %> <% end %>
<h1>New Transaction</h1>
</header>
<section class="form-wrapper" id="new-category-form">
<%= form_with model: @new_entity, url: group_entities_path, html: { method: :post } do |f| %>
 <div class="field">
 <%= f.text_field :name, placeholder: "Name" %>
 </div>
 <div class="field">
 <%= f.number_field :amount, placeholder: "Amount" %>
 </div>
 <div class="field">
  <%= f.collection_select :group_id, @user_groups, :id, :name %>
 </div> 
 <%= f.hidden_field :author_id, value: current_user.id %>
 <div class="field" >
<%= f.submit :ADD, class: 'btn-add'%>
</div>
<% end %>
</section>

app/views/groups/index.html.erb
<header class="page-header">
<%= link_to home_pages_path do %><%= image_tag "left-arrow.png", class: "nav-icon" %> <% end %>
<h1>Categories</h1>
<%# <span><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-5.197-5.197m0 0A7.5 7.5 0 105.196 5.196a7.5 7.5 0 0010.607 10.607z" />
</svg>
</span> %>
<%= button_to "Sign out", destroy_user_session_path , method: :delete %>
</header>
<section>
 <div class="cards-container">
 <% if @groups.present? %>
   <% @groups.each do |group| %>
   <a class="card-link-wrapper" href="<%= group_entities_path(group) %>">
   <div class="card">
   <div class="img-plchldr column"><img src="<%= group.icon %>"></div>
   <div class="column">
   <span><%= group.name %></span>
   <span class="date-stamp"><%= group.date %></span>
   </div>
   <div class="column last-col">
   <span class="sec-text"><%= group.total_amount %></span>
   <%# <span><%= button_to image_tag(), group_path(group.id), method: :delete, class: "del-group-btn btn-icon"%>
   </div>
 </div>
 </a>
 <% end %>
 <% else %>
        <div class="actions">
            You don't have any Group yet! Create one.
        </div>
    <% end %>
 <%= link_to "ADD CATEGORY", new_group_path, class: "btn-add" %>
 </div>
</section>

app/views/groups/new.html.erb
<header class="page-header">
<h1>New Category</h1>
</header>
<section class="form-wrapper" id="new-category-form">
<%= form_for @group, url: groups_path, html: { method: :post } do |f| %>
 <div class="field">
 <%= f.text_field :name, placeholder: "Name" %>
 </div>
 <div class="field">
 <%= f.text_field :icon, placeholder: "Icon URL", class: "last-input" %>
 </div>
 <div class="field" >
<%= f.submit :CREATE, class: "btn-add" %>
</div>
<% end %>
</section>

app/views/home/index.html.erb
<section class="First-page">
<header>
<h1 class="header">Budget App</h1>
</header>
<nav>
 <%= link_to "SIGN IN", :new_user_session, class: "btn blue-btn" %><br /><br>
 <%= link_to "SIGN UP", :new_user_registration, class: "btn gray-btn" %>
</nav>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>